version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_node
    restart: always
    ports:
      - ${NODE_PORT}:3030
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - PORT=${NODE_PORT}
    networks:
      - app_network
  db:
    image: mysql
    container_name: app_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: app_mysql_db_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

volumes:
  node:
    driver: local

networks:
  app_network:
    driver: bridge
